const projectsData = [
    { name: 'Leonardo DiCaprio Detector', 
        year: 2023, 
        icon: '💻', 
        tools: 'Python (OpenCV, Tensorflow Keras)', 
        github: 'https://github.com/kailyl/CIS-581-final-project' },
    { name: 'Pine - A Personalized News App', 
        year: 2023, 
        icon: '💻', 
        tools: 'NodeJS, ReactJS',
        github: 'https://github.com/kailyl/cis-4120-pine' },
    { name: 'Final Portfolio - Art, Design, and Digital Culture', 
        year: 2023, 
        icon: '🎨',
        tools: 'Adobe Illustrator, Photoshop, InDesign' },
    { name: 'EDA and Prediction on Global Temperature Data Since 1750', 
        year: 2023, 
        icon: '💻',
        tools: 'Python (Pandas, NumPy, Scikit Learn, Tensorflow Keras)',
        github: 'https://github.com/kailyl/temperature-analysis' },
    { name: 'Spotify Dashboard (Data)', 
        year: 2023, 
        icon: '💻',
        tools: 'Python, AWS (DynamoDB, Lambda, EventBridge)', 
        github: 'https://github.com/kailyl/spotify-dashboard-data' },
    { name: 'Spotify Dashboard', 
        year: 2023, 
        icon: '💻', 
        tools: 'NodeJS, ReactJS, AWS (DynamoDB)', 
        github: 'https://github.com/kailyl/spotify-dashboard' },
    { name: 'BenBook - The Penn Facebook', 
        year: 2022, 
        icon: '💻',
        tools: 'NodeJS, Java, AWS (DynamoDB, S3, EC2, EMR)',
        github: 'https://github.com/kailyl/benbook' },
    { name: 'Final Portfolio - Drawing I', 
        year: 2022, 
        icon: '🎨',
        tools: 'Charcoal, Pencil, Ink' },
    { name: 'Plotify', 
        year: 2022, 
        icon: '💻',
        tools: 'ReactJS',
        github: 'https://github.com/kailyl/plotifyapp.github.io' },
    { name: 'Common Onion Twitter Bot', 
        year: 2022, 
        icon: '💻',
        tools: 'Python',
        github: 'https://github.com/kailyl/the-onion-twitter-bot' },
    { name: 'Understanding the Relationship Between Seniority and Congressional Committee', 
        year: 2022, 
        icon: '💻',
        tools: 'Java', 
        github: 'https://github.com/kailyl/nets-150-final-project' },
    { name: 'Modified 2048', 
        year: 2021, 
        icon: '💻', 
        tools: 'Java', 
        github: 'https://github.com/kailyl/2048' },
    { name: 'kailyliu.com', 
        year: '∞', 
        icon: '💻',
        tools: 'NextJS, Typescript, ReactJS', 
        github: 'https://github.com/kailyl/my-portfolio' },
];

export default projectsData;